CREATE TABLE Watches (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Manufacturer NVARCHAR(100),
    Model NVARCHAR(100),
    ReleaseYear INT,
    Type NVARCHAR(50),
    Movement NVARCHAR(50),
    WaterResistance INT,
    CaseMaterial NVARCHAR(100),
    Functions NVARCHAR(255),
    Category NVARCHAR(50)
);

INSERT INTO Watches 
(Manufacturer, Model, ReleaseYear, Type, Movement, WaterResistance, CaseMaterial, Functions, Category)
VALUES
('Rolex','Submariner',1953,'analog','automatic',300,'stainless steel','dátum, forgatható lünetta','luxury'),
('Rolex','Datejust',1945,'analog','automatic',100,'stainless steel','dátum','luxury'),
('Rolex','Daytona',1963,'analog','automatic',100,'stainless steel','kronográf','luxury'),
('Omega','Speedmaster Professional',1957,'analog','manual',50,'stainless steel','kronográf, tachymeter','luxury'),
('Omega','Seamaster Diver 300M',1993,'analog','automatic',300,'stainless steel','dátum, héliumszelep','luxury'),
('Omega','Constellation',1952,'analog','automatic',100,'steel/gold','dátum','luxury'),
('Patek Philippe','Nautilus',1976,'analog','automatic',120,'stainless steel','dátum','luxury'),
('Patek Philippe','Aquanaut',1997,'analog','automatic',120,'composite','dátum','luxury'),
('Patek Philippe','Calatrava',1932,'analog','manual',30,'gold','csak idő','luxury'),
('Audemars Piguet','Royal Oak',1972,'analog','automatic',50,'stainless steel','dátum','luxury'),
('Audemars Piguet','Royal Oak Offshore',1993,'analog','automatic',100,'steel','kronográf','luxury'),
('Vacheron Constantin','Overseas',1996,'analog','automatic',150,'steel','dátum','luxury'),
('Vacheron Constantin','Patrimony',2004,'analog','manual',30,'gold','csak idő','luxury'),
('Seiko','5 Sports',1963,'analog','automatic',100,'stainless steel','nap-dátum','midrange'),
('Seiko','Presage',2010,'analog','automatic',50,'steel','dátum','midrange'),
('Seiko','Prospex Diver',1965,'analog','automatic',200,'steel','dátum, forgatható lünetta','midrange'),
('Citizen','Promaster Diver',1989,'analog','eco-drive',200,'steel','dátum','midrange'),
('Citizen','Chronomaster',1995,'analog','quartz',100,'steel','dátum','midrange'),
('Citizen','Nighthawk',2002,'analog','eco-drive',200,'steel','GMT, logarléc','midrange'),
('Casio','G-Shock DW-5600',1983,'digital','quartz',200,'resin','ébresztő, stopper, háttérvilágítás','sport'),
('Casio','G-Shock GA-2100',2019,'analog-digital','quartz',200,'resin','világidő, ébresztő','sport'),
('Casio','Edifice EFV-550',2015,'analog','quartz',100,'steel','kronográf','midrange'),
('Casio','F91W',1989,'digital','quartz',30,'resin','ébresztő, stopper','budget'),
('Tissot','PRX',1978,'analog','quartz/automatic',100,'steel','dátum','midrange'),
('Tissot','Le Locle',2003,'analog','automatic',30,'steel','dátum','midrange'),
('Hamilton','Khaki Field',1960,'analog','automatic',50,'steel','dátum','midrange'),
('Hamilton','Khaki Aviation',1999,'analog','automatic',100,'steel','kronográf','midrange'),
('Longines','HydroConquest',2007,'analog','automatic',300,'steel','dátum, forgatható lünetta','midrange'),
('Longines','Master Collection',2005,'analog','automatic',30,'steel','dátum, holdfázis','midrange'),
('TAG Heuer','Monaco',1969,'analog','automatic',100,'steel','kronográf','luxury'),
('TAG Heuer','Carerra',1963,'analog','automatic',100,'steel','kronográf','luxury'),
('Breitling','Navitimer',1952,'analog','automatic',30,'steel','kronográf, logarléc','luxury'),
('Breitling','Superocean',1957,'analog','automatic',300,'steel','dátum','luxury'),
('IWC','Big Pilot',1940,'analog','automatic',60,'steel','dátum','luxury'),
('IWC','Portugieser',1939,'analog','automatic',30,'steel','kronográf','luxury'),
('Panerai','Luminor',1950,'analog','manual',300,'steel','dátum','luxury'),
('Panerai','Radiomir',1936,'analog','manual',100,'steel','csak idő','luxury'),
('Oris','Aquis',2011,'analog','automatic',300,'steel','dátum','midrange'),
('Oris','Big Crown',1938,'analog','automatic',50,'steel','mutatós dátum','midrange'),
('Rado','HyperChrome',2012,'analog','automatic',100,'ceramic','dátum','midrange'),
('Rado','Centrix',2010,'analog','quartz',30,'ceramic','dátum','midrange'),
('Swatch','Original Gent',1983,'analog','quartz',30,'plastic','csak idő','budget'),
('Swatch','Irony Chrono',1994,'analog','quartz',30,'steel','kronográf','budget'),
('Apple','Watch Series 9',2023,'digital','smart',50,'aluminum','fitnesz követés, GPS, értesítések','smartwatch'),
('Samsung','Galaxy Watch 6',2023,'digital','smart',50,'aluminum','fitnesz követés, GPS','smartwatch'),
('Garmin','Fenix 7',2022,'digital','smart',100,'polymer','GPS, magasságmérő, pulzusmérés','smartwatch'),
('Huawei','Watch GT 3',2021,'digital','smart',50,'steel','fitnesz követés, GPS','smartwatch'),
('Xiaomi','Mi Watch',2020,'digital','smart',50,'aluminum','fitnesz követés, GPS','budget'),
('Fossil','Gen 6 Smartwatch',2021,'digital','smart',30,'steel','értesítések, pulzusmérés','smartwatch'),
('Timex','Weekender',2010,'analog','quartz',30,'brass','indiglo világítás','budget'),
('Timex','Ironman',1986,'digital','quartz',100,'resin','stopper, ébresztő','sport');